# API Evangelist Portal (Minimum Viable)

# This is mean to be a simple example of a portal for any API.
# It provides a forkable portal, with checklist any API provider can follow.
# It uses Jekyl, and can be controlled mostly via this _config.yml page.

# Kin Lane
# http://apievangelist.com
# @kinlane

# Portal
# Every API should have a simple portal providing access to the API and all supporting resources.

# Name - Provide a simple name for your API / developer portal.
portal_name: 'Minimum Viable API Portal'

# URL - developer.[yourdomain].com
portal_url: http://portal.minimum.apievangelist.com

# Description - Provide a concise description of what a platform does.
portal_description: 'What does this platform do? What solutions do the APIs provide? Keep short as possible.'

#Getting Started - Give everyone, even non-developers as place to start, helping us understand what is needed to get started with API integration, from signing up for an account to where do I find support.
getting_started:
  - title: Getting Started With The API
    description: This is the description for the getting started section of this API.
    # The link to signup for developer access
    signup_url: http://developer.apievangelist.com/signup
    # The link to login as developer
    login_url: : http://developer.apievangelist.com/login
    # The link to create a new application
    create_app_url: http://developer.apievangelist.com/user/app/create
    footer: This is the description for the getting started section of this API.
